parameters:
#    bet_main.example.class: Bet\MainBundle\Example

services:
#    bet_main.example:
#        class: %bet_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
